//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hombay
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HomeBeyDBEntities : DbContext
    {
        public HomeBeyDBEntities()
            : base("name=HomeBeyDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Category> tbl_Category { get; set; }
        public virtual DbSet<tbl_items> tbl_items { get; set; }
        public virtual DbSet<tbl_users> tbl_users { get; set; }
        public virtual DbSet<tbl_Review> tbl_Review { get; set; }
        public virtual DbSet<tbl_new_construction> tbl_new_construction { get; set; }
        public virtual DbSet<tbl_Rating> tbl_Rating { get; set; }
        public virtual DbSet<tbl_contact> tbl_contact { get; set; }
        public virtual DbSet<tbl_Complaints> tbl_Complaints { get; set; }
        public virtual DbSet<tbl_Chat> tbl_Chat { get; set; }
        public virtual DbSet<tbl_proprogress> tbl_proprogress { get; set; }
        public virtual DbSet<tbl_Order> tbl_Order { get; set; }
        public virtual DbSet<User_Bidding> User_Bidding { get; set; }
        public virtual DbSet<tbl_cart_item> tbl_cart_item { get; set; }
    
        public virtual ObjectResult<Nullable<int>> sp_gettotaluser()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_gettotaluser");
        }
    
        public virtual ObjectResult<Nullable<int>> sp_gettotalBuyer()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_gettotalBuyer");
        }
    
        public virtual ObjectResult<Nullable<int>> sp_gettotallandowner()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_gettotallandowner");
        }
    
        public virtual ObjectResult<Nullable<int>> sp_gettotalSeller()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_gettotalSeller");
        }
    
        public virtual ObjectResult<Nullable<int>> sp_gettotalservicer()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_gettotalservicer");
        }
    
        public virtual ObjectResult<Nullable<int>> sp_gettotalbidding()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_gettotalbidding");
        }
    
        public virtual ObjectResult<Nullable<int>> sp_gettotalcomplaint()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_gettotalcomplaint");
        }
    
        public virtual ObjectResult<Nullable<int>> sp_gettotalItem()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_gettotalItem");
        }
    
        public virtual ObjectResult<Nullable<int>> sp_gettotalconstruction()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_gettotalconstruction");
        }
    
        public virtual ObjectResult<Nullable<int>> sp_Usercomplaints(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_Usercomplaints", idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_UserQuery(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_UserQuery", idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_UserReviews(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_UserReviews", idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_landownerConscount(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_landownerConscount", idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_landownerquansum(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_landownerquansum", idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_SellerItemcount(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_SellerItemcount", idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_SellerItemprice(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_SellerItemprice", idParameter);
        }
    
        public virtual ObjectResult<sp_getrecentscreenshots_Result> sp_getrecentscreenshots(Nullable<int> startId, Nullable<int> endId)
        {
            var startIdParameter = startId.HasValue ?
                new ObjectParameter("startId", startId) :
                new ObjectParameter("startId", typeof(int));
    
            var endIdParameter = endId.HasValue ?
                new ObjectParameter("endId", endId) :
                new ObjectParameter("endId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getrecentscreenshots_Result>("sp_getrecentscreenshots", startIdParameter, endIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_BuyerAccBid(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_BuyerAccBid", idParameter);
        }
    
        public virtual int sp_BuyerBid(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_BuyerBid", idParameter);
        }
    
        public virtual ObjectResult<sp_livechat_Result> sp_livechat(string user1, string user2)
        {
            var user1Parameter = user1 != null ?
                new ObjectParameter("User1", user1) :
                new ObjectParameter("User1", typeof(string));
    
            var user2Parameter = user2 != null ?
                new ObjectParameter("User2", user2) :
                new ObjectParameter("User2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_livechat_Result>("sp_livechat", user1Parameter, user2Parameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_AddContructionAddBid(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_AddContructionAddBid", idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_MypurchaseItem(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_MypurchaseItem", idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_Myprojects(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_Myprojects", idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_paidItemprice(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_paidItemprice", idParameter);
        }
    
        public virtual ObjectResult<sp_Userchats_Result> sp_Userchats(string name1, string name2)
        {
            var name1Parameter = name1 != null ?
                new ObjectParameter("name1", name1) :
                new ObjectParameter("name1", typeof(string));
    
            var name2Parameter = name2 != null ?
                new ObjectParameter("name2", name2) :
                new ObjectParameter("name2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Userchats_Result>("sp_Userchats", name1Parameter, name2Parameter);
        }
    }
}
