//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hombay
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_proprogress
    {
        public int Pro_id { get; set; }
        public Nullable<int> User_id { get; set; }
        public string Project_name { get; set; }
        public Nullable<int> Progress { get; set; }
        public Nullable<int> Servicer_id { get; set; }
        public string Image { get; set; }
    }
}
