//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hombay
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Chat
    {
        public int Id { get; set; }
        public Nullable<int> Sender_id { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string Sender_user { get; set; }
        public string Message { get; set; }
        public Nullable<int> Receiver_id { get; set; }
        public string Receiver_user { get; set; }
        public string Sender { get; set; }
    }
}
