//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hombay
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Bidding
    {
        public int Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public string Item_Name { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> Date_from { get; set; }
        public Nullable<System.DateTime> Date_to { get; set; }
        public string price { get; set; }
        public string Bid_amount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Item_Id { get; set; }
        public string Approve { get; set; }
        public string Image { get; set; }
        public Nullable<int> Buyer_Id { get; set; }
    }
}
